In [9]:
import numpy as np

In [10]:
X = np.arange(1, 51)

In [11]:
X = np.array(X)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
np.random.rand(2)

array([0.30170264, 0.8582349 ])

In [13]:
for x in X:
    print(x)
    break

1


In [14]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

In [15]:
def func(X):
    return X * 2


transformed_func = FunctionTransformer(func)

pipeline = Pipeline([("custom_step", transformed_func)])


print(pipeline.fit_transform(X))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [2]:
import numpy as np

In [5]:
X = np.array([[1, 2], [3, 4], [8, 5]])
y = np.array([[3], [7], [12]])

In [6]:
X, y

(array([[1, 2],
        [3, 4],
        [8, 5]]),
 array([[ 3],
        [ 7],
        [12]]))

In [11]:
x_t = X.T
x_t

array([[1, 3, 8],
       [2, 4, 5]])

In [13]:
A = np.dot(x_t, X)
A

array([[74, 54],
       [54, 45]])

In [15]:
inverse = np.linalg.inv(A)
inverse

array([[ 0.10869565, -0.13043478],
       [-0.13043478,  0.17874396]])

In [18]:
result = np.dot(np.dot(inverse, x_t), y)
result

array([[0.7826087 ],
       [1.14975845]])